server:
  port: 8686
  servlet:
    context-path: /time/manage
spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.sdw.timemanage.mapper
  mapper-locations: classpath:mapper/*.xml