spring:
  datasource:
    url: jdbc:mysql://localhost:3306/time_manage?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: sdw123
    driver-class-name: com.mysql.jdbc.Driver

